[package]
name = "sauth_server2"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.4"
jsonwebtoken = "9.3.1"
serde = "1.0.219"
serde_json = "1.0.140"
tokio = { version = "1.45", features = ["full"] }
